const scenario={title:'Construis un turboréacteur',steps:[
 {type:'SITUATION',tag:'Objectif',title:'Tu dois produire de la poussée.',body:'Tu disposes d’un simple ventilateur. Ton objectif est d’obtenir davantage de poussée sans changer le principe de base.',choices:[['Augmenter le flux d’air','Le ventilateur accélère l’air : la quantité de mouvement transmise à l’air produit une poussée. Mais elle reste faible.','Ventilation'],['Peindre le ventilateur','La couleur ne modifie pas significativement le transfert de quantité de mouvement.','—']]},
 {type:'PROBLÈME',tag:'Flux',title:'La poussée reste insuffisante.',body:'Tu ajoutes plusieurs rangées de pales. Pourtant, le gain attendu n’apparaît pas : le flux sort du premier étage avec une mauvaise orientation.',choices:[['Ajouter des aubes fixes','Bonne intuition : des aubes fixes peuvent redresser et orienter le flux vers l’étage suivant.','Aubes directrices'],['Ajouter une batterie plus grosse','Cela augmente la puissance disponible, mais ne résout pas directement la mauvaise orientation du flux.','—']]},
 {type:'DÉCOUVERTE',tag:'Compression',title:'Il faut maintenant augmenter la pression.',body:'Tu enchaînes plusieurs étages de compression et réduis progressivement le passage. L’air est comprimé et sa pression augmente.',choices:[['Continuer les étages','Chaque étage ajoute du travail au flux et augmente progressivement le rapport de pression.','Compresseur'],['Ouvrir davantage le tube','Tu diminuerais la compression au lieu de l’augmenter.','—']]},
 {type:'PROBLÈME',tag:'Énergie',title:'L’air comprimé n’a pas encore assez d’énergie.',body:'Tu as de l’air chaud et comprimé, mais tu veux accélérer fortement les gaz à la sortie.',choices:[['Ajouter une chambre de combustion','Le carburant brûle dans l’air comprimé et ajoute de l’énergie au flux, augmentant fortement sa température.','Combustion'],['Refroidir l’air','Cela retire de l’énergie au flux et va dans la direction opposée.','—']]},
 {type:'PROBLÈME',tag:'Autonomie',title:'Le système dépend encore du moteur.',body:'Le compresseur est toujours entraîné par un moteur externe. Si le moteur s’arrête, le cycle s’arrête.',choices:[['Récupérer l’énergie des gaz','Une turbine placée dans le flux chaud peut extraire une partie de l’énergie des gaz et entraîner le compresseur.','Turbine'],['Ajouter une seconde batterie','Cela conserve la dépendance à une source électrique externe.','—']]},
 {type:'SYNTHÈSE',tag:'Système',title:'Tu viens de construire un turboréacteur.',body:'Le compresseur comprime l’air, la combustion ajoute de l’énergie, la turbine récupère une partie de cette énergie et entraîne le compresseur. Les gaz restants sont accélérés par la tuyère pour produire la poussée.',choices:[]}
]};

const state={step:0,score:0,discovered:[]};
const $=s=>document.querySelector(s);
function renderGraph(){const concepts=['Ventilation','Aubes directrices','Compresseur','Combustion','Turbine','Tuyère'];$('#graph').innerHTML=concepts.map((x,i)=>`<div class="node ${state.discovered.includes(x)?'discovered':''} ${state.step===i?'active':''}"><strong>${x}</strong><small>${state.discovered.includes(x)?'concept découvert':'à découvrir'}</small></div>`).join('');$('#mastery').textContent=Math.round(state.discovered.length/concepts.length*100)+'%'}
function render(){const s=scenario.steps[state.step];$('#stepLabel').textContent=`Étape ${state.step+1} / ${scenario.steps.length}`;$('#progressBar').style.width=((state.step+1)/scenario.steps.length*100)+'%';$('#stageType').textContent=s.type;$('#conceptTag').textContent=s.tag;$('#title').textContent=s.title;$('#body').textContent=s.body;$('#feedback').classList.add('hidden');$('#next').classList.add('hidden');$('#choices').innerHTML=s.choices.map((c,i)=>`<button class="choice" data-i="${i}">${String.fromCharCode(65+i)}. ${c[0]}</button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(+b.dataset.i));renderGraph()}
function choose(i){const s=scenario.steps[state.step],c=s.choices[i];document.querySelectorAll('.choice').forEach(b=>b.disabled=true);const good=i===0;state.score+=good?1:0;if(good&&!state.discovered.includes(c[2])&&c[2]!=='—')state.discovered.push(c[2]);$('#feedback').textContent=(good?'Bonne décision. ':'Pas optimal. ')+c[1];$('#feedback').classList.remove('hidden');$('#next').classList.remove('hidden');renderGraph()}
$('#next').onclick=()=>{if(state.step<scenario.steps.length-1){state.step++;render()}else{$('#next').textContent='Rejouer';state.step=0;state.score=0;state.discovered=[];render()}};render();
