# -*- coding: utf-8 -*-
"""Laboratoire : templates d'expériences jouables (21, couvrant 12 domaines) + suggestions de formulaire."""

def _t(tid, title, cat, sim, desc, **kw):
    d = {"id": tid, "title": title, "category": cat, "sim_type": sim, "description": desc,
         "hypothesis": kw.get("h", ""), "iv": kw.get("iv", ""), "iv_levels": kw.get("ivl", ""),
         "dv": kw.get("dv", ""), "dv_measure": kw.get("dvm", ""), "design": kw.get("design", "Intra-sujet"),
         "population": kw.get("pop", "Adultes"), "n": kw.get("n", 30), "material": kw.get("mat", "Écran + clavier"),
         "procedure": kw.get("proc", ""), "controls": kw.get("ctrl", ""), "ethics": kw.get("eth", "Consentement éclairé, anonymat"),
         "expected": kw.get("exp", ""), "concepts": kw.get("conc", ""), "status": "template", "n_trials": kw.get("nt", 20)}
    return d

TEMPLATES = [
    # ── Cognitive — Attention (3)
    _t("tmpl_stroop", "Effet Stroop — Interférence couleur-mot", "Cognitive — Attention", "stroop",
        "Nommer la couleur d'encre de mots incongruents coûte du temps : mesure du contrôle inhibiteur.",
        h="Le TR de nommage sera plus long en condition incongruente qu'en condition congruente (Δ > 40 ms).",
        iv="Congruence (mot vs couleur)", ivl="Congruent | Incongruent | Neutre",
        dv="Temps de réaction (ms) + erreurs", dvm="Chronométrage automatique par essai",
        mat="Écran + clavier (touches R/B/V/J)", nt=21,
        proc="1. Instructions et 4 essais d'entraînement. 2. 21 essais randomisés (7 par condition). 3. Le stimulus s'affiche, répondre à la couleur d'encre via la touche. 4. Feedback court (✓/✗) entre essais.",
        ctrl="Ordre randomisé, même touches pour tous, pauses visuelles constantes, luminance équilibrée.",
        exp="Effet Stroop classique : TR inc > TR congruent de 60-120 ms chez l'adulte jeune.",
        conc="Charge cognitive, contrôle attentionnel, fonctions exécutives"),
    _t("tmpl_flanker", "Paradigme Flanker — Attention sélective", "Cognitive — Attention", "flanker",
        "Identifier la direction de la flèche centrale au sein de distracteurs congruents ou incongruents.",
        h="Le TR sera plus long dans la condition incongruente (<<><<) que congruente (<<<<<).",
        iv="Congruence flanker", ivl="Congruent | Incongruent | Neutre",
        dv="TR (ms) + taux d'erreurs", dvm="Touches flèches ← →",
        mat="Écran + clavier (flèches)", nt=21,
        proc="1. Entraînement (5 essais). 2. 21 essais : la flèche centrale apparaît 500 ms après un point de fixation. 3. Répondre à la direction de la flèche CENTRALE.",
        ctrl="SOA constant, randomisation, équilibrage gauche/droite.",
        exp="Effet flanker de 40-80 ms chez l'adulte.",
        conc="Attention sélective, inhibition, fonctions exécutives"),
    _t("tmpl_posner", "Cueing de Posner — Attention spatiale", "Cognitive — Attention", "posner",
        "Un indice spatial (valide ou non) précède une cible : mesure des coûts/bénéfices de l'orientation attentionnelle.",
        h="TR cible valide < neutre < invalide (bénéfice + coût d'orientation).",
        iv="Validité de l'indice", ivl="Valide (80%) | Invalide (20%)",
        dv="TR de détection (ms)", dvm="Touche espace dès la cible détectée",
        mat="Écran, indices périphériques", nt=20,
        proc="1. Fixation centrale. 2. Indice (flash à gauche/droite). 3. Cible après 300 ms — appuyer ESPACE. 4. 80% d'essais valides.",
        ctrl="ISI constant, proportion validité fixée, randomisation.",
        exp="Bénéfice valide ≈ -40 ms, coût invalide ≈ +40 ms vs neutre.",
        conc="Attention spatiale, covert attention, cueing"),
    # ── Cognitive — Mémoire (3)
    _t("tmpl_nback", "Tâche N-back — Mémoire de travail", "Cognitive — Mémoire", "nback",
        "Indiquer si la lettre correspond à celle d'il y a 2 présentations : mise à jour de la MdT.",
        h="La performance (d') sera inférieure en 2-back vs 1-back.",
        iv="Charge N", ivl="1-back | 2-back",
        dv="Hits, fausses alertes, d'", dvm="Théorie de la détection du signal",
        mat="Écran + touche espace", nt=30,
        proc="1. Entraînement 1-back. 2. 30 lettres présentées 1,8 s chacune. 3. ESPACE quand la lettre = celle d'il y a 2. 4. ~30% de cibles.",
        ctrl="Probabilité de cibles fixée, timing constant, interdiction de compter à voix haute.",
        exp="d' 2-back ≈ 1.5-2.5 chez l'adulte jeune ; FA ↑ avec la charge.",
        conc="Mémoire de travail, mise à jour, validité du n-back (Huang 2025)"),
    _t("tmpl_drm", "Faux souvenirs (DRM — Deese-Roediger-McDermott)", "Cognitive — Mémoire", "drm",
        "Étudier des listes de mots associés à un leurre non-présenté : le leurre est souvent « rappelé » comme vu.",
        h="Le taux de fausses reconnaissances du leurre critique sera proche du taux de succès des mots étudiés.",
        iv="Type d'item au test", ivl="Étudiés | Leurre critique | Neufs",
        dv="Taux de reconnaissance (« vu »)", dvm="Pourcentage par type d'item",
        mat="Écran, listes de mots associatifs", nt=12,
        proc="1. Phase d'étude : 12 mots (1,2 s chacun). 2. Distracteur (compte à rebours). 3. Reconnaissance : 12 items — « Vu ou Nouveau ? ».",
        ctrl="Équilibrage ordre, listes de force associative constante.",
        exp="Faux souvenir du leurre ≈ 60-80% (proche des mots réellement étudiés).",
        conc="Faux souvenirs, Loftus, mémoire reconstructive"),
    _t("tmpl_testing", "Testing Effect — L'effet du test", "Cognitive — Mémoire", "testing",
        "Récupérer l'information (se tester) consolide plus que relire.",
        h="Le rappel final sera meilleur pour les paires testées que pour les paires relues.",
        iv="Stratégie d'étude", ivl="Test (récupération) | Relecture",
        dv="Rappel final (%)", dvm="QCM final sur 6 paires",
        mat="Écran, paires mot-définition", nt=6,
        proc="1. Étude de 6 paires. 2. Pour 3 paires : QCM immédiat. Pour 3 autres : relecture. 3. Test final sur les 6.",
        ctrl="Contrebalancement des stratégies, paires équivalentes.",
        exp="Avantage du test ≈ +15-30% au rappel final.",
        conc="Testing effect, consolidation, apprentissage"),
    # ── Sociale (3)
    _t("tmpl_asch", "Conformité d'Asch — Pression de groupe", "Sociale — Conformité", "asch",
        "Juger des longueurs de lignes face à une majorité unanime (simulée) qui donne parfois une mauvaise réponse.",
        h="Le taux de conformité sera significatif (>25%) dans les essais critiques.",
        iv="Réponse du groupe (unanime)", ivl="Essais neutres | Essais critiques (majorité fausse)",
        dv="Taux de conformité (%)", dvm="Proportion d'essais où l'on suit la majorité erronée",
        mat="Écran, lignes de référence", nt=12,
        proc="1. Comparer la ligne cible à 3 options. 2. Les « participants » virtuels répondent d'abord. 3. Dans 8 essais critiques, tous donnent la même mauvaise réponse. 4. Répondre ensuite.",
        ctrl="Longueurs distinctes (7/9 cm), position de la bonne réponse contrebalancée.",
        exp="Conformité ≈ 30-37% des essais critiques (Asch 1951 : 75% se conforment au moins 1 fois).",
        conc="Conformité, Asch, normes sociales"),
    _t("tmpl_exposure", "Effet de simple exposition (Zajonc)", "Sociale — Attitudes", "exposure",
        "Des stimuli simplement répétés deviennent plus appréciés.",
        h="La préférence croîtra avec la fréquence de présentation.",
        iv="Fréquence de présentation", ivl="0 | 1 | 2 | 5 | 10 | 25",
        dv="Liking (1-7)", dvm="Corrélation rang (Spearman) fréquence-liking",
        mat="Écran, formes abstraites", nt=6,
        proc="1. Phase d'exposition : 43 slides (formes à fréquences variées). 2. Phase d'évaluation : noter chaque forme (1-7).",
        ctrl="Ordre randomisé, formes équilibrées en complexité.",
        exp="Corrélation positive fréquence-liking (ρ ≈ 0.5-0.8) chez la plupart des participants.",
        conc="Exposition (Zajonc 1968), attitudes, familiarité"),
    _t("tmpl_bystander", "Effet du spectateur", "Sociale — Prosocial", "bystander",
        "Plus il y a de témoins, moins chacun aide (diffusion de responsabilité).",
        h="La probabilité d'aider diminue avec le nombre de témoins présents.",
        iv="Nombre de témoins", ivl="Seul | 1 autre | 4 autres",
        dv="Décision d'aider (%) + latence", dvm="Choix par scénario",
        mat="Écran, scénarios d'urgence", nt=6,
        proc="1. Lire 6 scénarios d'urgence. 2. Chaque scénario précise le nombre d'autres témoins. 3. Décider : aider ou non + latence de réponse.",
        ctrl="Gravité des scénarios équilibrée, ordre randomisé.",
        exp="Aide plus fréquente seul (~85%) qu'à 4+ (~30-50% selon scénarios).",
        conc="Darley & Latané, diffusion de responsabilité, aide"),
    # ── Décision — Biais (3)
    _t("tmpl_framing", "Effet de cadrage — Asian disease", "Décision — Biais", "framing",
        "Le même problème formulé en gains vs pertes inverse les préférences (réseau de Kahneman & Tversky).",
        h="Cadrage gains → choix sûr ; cadrage pertes → choix risqué.",
        iv="Cadrage", ivl="Gains (200 sauvés) | Pertes (400 morts)",
        dv="Choix (sûr vs risqué)", dvm="Distribution des choix par condition",
        mat="Écran, scénario assigné aléatoirement", nt=1,
        proc="1. Assignation aléatoire du cadrage. 2. Lecture du problème (épidémie, 600 personnes). 3. Choix entre programme sûr et risqué. 4. Débriefing (les 2 versions).",
        ctrl="Équivalence logique stricte des options (200/600).",
        exp="~72% choisissent le programme sûr en gains ; ~22% en pertes (K&T 1981).",
        conc="Framing, prospect theory, aversion aux pertes"),
    _t("tmpl_anchoring", "Ancrage — Roue de fortune", "Décision — Biais", "anchoring",
        "Estimer un pourcentage après avoir vu un nombre aléatoire (ancre).",
        h="L'estimation sera tirée vers l'ancre, même aléatoire.",
        iv="Ancre", ivl="Basse (10) | Haute (65)",
        dv="Estimation numérique (%)", dvm="Écart moyen à la valeur réelle (~28%) par condition",
        mat="Écran, roue animée + champ de saisie", nt=1,
        proc="1. Roue de fortune (déterminée) affiche 10 ou 65. 2. Estimer le % de pays africains à l'ONU. 3. Débriefing (vraie valeur ≈ 28%).",
        ctrl="Ancres assignées aléatoirement, source présentée comme aléatoire.",
        exp="Ancre 10 → ≈ 25% ; ancre 65 → ≈ 45% (Tversky & Kahneman 1974).",
        conc="Ancrage, ajustement insuffisant, heuristiques"),
    _t("tmpl_sunkcost", "Coûts irrécupérables", "Décision — Biais", "sunkcost",
        "Continuer à investir à cause de ce qui est déjà dépensé, pas des bénéfices futurs.",
        h="La persistance sera plus fréquente quand l'investissement passé est saillant.",
        iv="Salience de l'investissement passé", ivl="Investissement élevé | Faible",
        dv="Choix de persistance (%)", dvm="Proportion de « continuer » par scénario",
        mat="Écran, 6 scénarios appariés", nt=6,
        proc="1. Lire 6 scénarios (projet, billets, voiture…). 2. Choisir : continuer ou abandonner. 3. Débriefing sur la rationalité.",
        ctrl="Scénarios appariés (version investie/non-investie) contrebalancés.",
        exp="Persistance majoritaire (>60%) dans les versions à investissement élevé.",
        conc="Coûts irrécupérables, Arkes & Blumer, escalade"),
    # ── Métacognition (2)
    _t("tmpl_calibration", "Calibration métacognitive (JOL)", "Métacognition", "calibration",
        "Prédire sa mémoire (JOL) puis vérifier : confiance vs performance.",
        h="La confiance excédera la performance (surconfiance) ; le gamma sera < 1.",
        iv="Phase (prédiction vs réalisation)", ivl="JOL (0-100%) | Rappel réel",
        dv="Biais de calibration (confiance - exactitude)", dvm="Écart moyen + gamma de Goodman-Kruskal",
        mat="Écran, 8 paires mot-mot", nt=8,
        proc="1. Étude de 8 paires (4 s chacune). 2. JOL pour chaque paire (0-100%). 3. Test de rappel indice → choisir parmi 4 options. 4. Courbe de calibration.",
        ctrl="Ordre des JOL et du test randomisés, paires de difficulté moyenne.",
        exp="Surconfiance typique : confiance ≈ 75% vs rappel ≈ 55-65%.",
        conc="Métacognition, JOL, calibration, Flavell"),
    _t("tmpl_dunnkruger", "Dunning-Kruger — Auto-évaluation", "Métacognition", "dunnkruger",
        "Passer un mini-test puis s'auto-estimer : les faibles se surestiment.",
        h="L'écart estimation-réalité sera plus grand pour les scores faibles.",
        iv="Niveau de performance (quartile)", ivl="Faible | Moyen | Fort",
        dv="Écart percentile estimé - réel", dvm="Différence par quartile",
        mat="Quiz de culture générale (10 questions)", nt=10,
        proc="1. Quiz de 10 questions (culture générale psychologie). 2. Estimer son percentile (0-100). 3. Comparaison estimation vs réel.",
        ctrl="Questions calibrées de difficulté croissante, scoring objectif.",
        exp="Quartile faible : +40 à +50 points d'écart ; quartile fort : -5 à -10.",
        conc="Dunning-Kruger, métacognition, calibration"),
    # ── Développement (2)
    _t("tmpl_conservation", "Conservation (Piaget)", "Développement", "conservation",
        "Les enfants en stade pré-opératoire jugent que la quantité change quand la forme change.",
        h="Le stade pré-opératoire échoue aux épreuves de conservation (≈ avant 7 ans).",
        iv="Type d'épreuve", ivl="Liquide | Nombre | Masse | Longueur",
        dv="Réussite/échec par type", dvm="% de réussite par épreuve",
        mat="Illustrations animées (gobelets, jetons, pâte, bâtons)", nt=4,
        proc="1. 4 épreuves illustrées : transformation visible puis question « est-ce pareil ou différent ? ». 2. Vérification de la justification (choix parmi des raisons).",
        ctrl="Transformations standardisées, questions identiques entre épreuves.",
        exp="Réussite typique > 7 ans (stade opératoire concret).",
        conc="Piaget, stades, conservation, développement"),
    _t("tmpl_tom", "Théorie de l'esprit (Sally-Anne)", "Développement", "tom",
        "Attribuer une fausse croyance à autrui : la question clé de Wimmer & Perner.",
        h="Le succès (réponse « panier ») émerge vers 4-5 ans.",
        iv="Type de question", ivl="Fausse croyance | Réalité | Mémoire",
        dv="Réussite par type de question", dvm="% correct",
        mat="Histoire illustrée en 4 étapes", nt=3,
        proc="1. Histoire de Sally et Anne (4 illustrations). 2. 3 questions : où cherchera Sally ? où est vraiment la bille ? où l'a-t-elle posée ?",
        ctrl="Questions dans un ordre fixe, illustrations standardisées.",
        exp="Réussite fausse-croyance ~80% à 5 ans, ~30% à 3 ans (Wimmer & Perner 1983).",
        conc="Théorie de l'esprit, fausse croyance, ToM"),
    # ── Éducation (2)
    _t("tmpl_generation", "Effet de génération", "Éducation", "generation",
        "Générer l'information (compléter) encode mieux que la lire.",
        h="Le rappel des mots générés sera supérieur à celui des mots lus.",
        iv="Mode d'encodage", ivl="Généré (fragment) | Lu",
        dv="Rappel final (%)", dvm="% correct au test final",
        mat="Écran, 8 mots (4 générés, 4 lus)", nt=8,
        proc="1. Phase d'étude : 8 mots — 4 à compléter depuis un fragment (C__N_ → CHIEN), 4 à lire. 2. Tâche distractrice 30 s. 3. Rappel libre des 8 mots.",
        ctrl="Contrebalancement généré/lu, mots de fréquence similaire.",
        exp="Avantage de génération ≈ +15-25% de rappel (Slamecka & Graf 1978).",
        conc="Effet de génération, encodage, apprentissage actif"),
    _t("tmpl_spaced", "Répétition espacée vs massée", "Éducation", "spaced",
        "Espace les répétitions dans le temps consolide mieux que les masser.",
        h="La rétention sera meilleure pour les listes espacées.",
        iv="Distribution des répétitions", ivl="Espacée (intervalle) | Massée (consécutive)",
        dv="Rappel final (%)", dvm="% correct au test final",
        mat="Écran, 2 listes de 5 paires", nt=10,
        proc="1. Liste A : 5 paires répétées 3x consécutives. 2. Tâche distractive 30 s. 3. Liste B : 5 paires répétées 3x avec intervalles. 4. Test final des 10 paires.",
        ctrl="Contrebalancement A/B, paires équivalentes.",
        exp="Avantage espacé ≈ +10-25% (Cepeda et al. 2006).",
        conc="Répétition espacée, consolidation, courbe d'oubli"),
    # ── Neurosciences (1)
    _t("tmpl_p300", "P300 — Paradigme Oddball", "Neurosciences", "oddball",
        "Détecter les stimuli rares (20%) : le compte rendu simule la mesure du P300.",
        h="Les stimuli rares sont détectés avec une précision > 90% et suscitent l'attention (indice de nouveauté).",
        iv="Type de stimulus", ivl="Standard (bleu, 80%) | Cible (rouge, 20%)",
        dv="Détections (hits), fausses alertes, TR", dvm="Comptage + d'",
        mat="Écran + touche espace", nt=30,
        proc="1. 30 cercles présentés (600 ms, ISI 700 ms). 2. ESPACE pour chaque cercle ROUGE. 3. Statistiques de détection.",
        ctrl="Proportions fixées, timing constant.",
        exp="d' > 3 typiquement ; TR cibles ≈ 400-500 ms.",
        conc="Oddball, P300, attention, potentiel évoqué"),
    # ── Personnalité (1)
    _t("tmpl_bigfive", "Mini Big Five (TIPI)", "Personnalité", "bigfive",
        "Profil OCEAN rapide (10 items, Gosling 2003).",
        h="Le profil reflète les 5 traits avec une cohérence interne acceptable.",
        iv="Items TIPI", ivl="10 items, Likert 1-7",
        dv="Scores OCEAN (1-7)", dvm="Moyenne des items (avec inversés)",
        mat="Questionnaire en ligne", nt=10,
        proc="1. 10 items (« je me vois comme… »). 2. Réponses 1-7. 3. Scores par trait (items inversés pour N, A).",
        ctrl="Items TIPI standardisés, formulation inchangée.",
        exp="Cohérence interne r≈0.6 (TIPI court), validité convergente avec NEO.",
        conc="Big Five, personnalité, OCEAN"),
    # ── Clinique (1)
    _t("tmpl_stroop_emo", "Stroop émotionnel", "Clinique", "stroop_emo",
        "Les mots menaçants captent l'attention et ralentissent le nommage (marqueur d'anxiété).",
        h="TR menaçant > TR neutre ; effet accru en anxiété trait/état.",
        iv="Valence émotionnelle du mot", ivl="Menaçant | Neutre | Positif",
        dv="TR de nommage de la couleur (ms)", dvm="ΔTR par valence",
        mat="Écran + clavier couleur", nt=24,
        proc="1. 24 mots (8 par valence) en couleurs aléatoires. 2. Nommage de la couleur (R/B/V/J). 3. ΔTR par valence.",
        ctrl="Luminance équilibrée, équilibrage des couleurs par valence.",
        exp="ΔTR menaçant-neutre ≈ +20-50 ms (plus grand en anxiété).",
        conc="Stroop émotionnel, anxiété, attention"),
]

# ─────────────── SUGGESTIONS d'autocomplétion (formulaire smart) ───────────────
SUGGESTIONS = {
    "title": ["Effet Stroop — Interférence couleur-mot", "Tâche N-back — Mémoire de travail", "Conformité d'Asch — Pression de groupe",
              "Effet de cadrage — Gain vs perte", "Calibration métacognitive — JOL", "Faux souvenirs — Paradigme DRM",
              "Flanker — Attention sélective", "Ancrage — Roue de fortune", "Coûts irrécupérables — Persistance",
              "Effet du spectateur — Diffusion de responsabilité", "Cueing de Posner — Attention spatiale",
              "Stroop émotionnel — Anxiété", "Big Five TIPI — Profil OCEAN", "Effet de génération — Encodage actif",
              "Répétition espacée vs massée", "Conservation piagétienne", "Théorie de l'esprit — Sally-Anne",
              "Iowa Gambling Task — Décision", "Effet de simple exposition — Zajonc", "P300 Oddball — Détection rare"],
    "hypothesis": ["Le TR sera plus long en condition incongruente qu'en condition congruente (Δ > 40 ms).",
                   "La performance (d') diminuera avec l'augmentation de la charge (N).",
                   "Le taux de conformité sera supérieur à 25% dans les essais critiques.",
                   "Le cadrage en pertes induira davantage de choix risqués que le cadrage en gains.",
                   "La confiance moyenne excédera l'exactitude réelle (biais de surconfiance).",
                   "Le taux de fausses reconnaissances du leurre critique sera proche de celui des mots étudiés.",
                   "La préférence croîtra avec la fréquence de présentation (exposition).",
                   "L'estimation sera tirée vers l'ancre, même présentée comme aléatoire.",
                   "La probabilité d'aider diminuera avec le nombre de témoins présents."],
    "iv": ["Congruence (mot-couleur)", "Charge de mémoire (N)", "Validité de l'indice", "Cadrage (gain vs perte)",
           "Type d'item (leurre/étudié/neuf)", "Nombre de témoins", "Ancre numérique", "Valence émotionnelle",
           "Fréquence de présentation", "Stratégie d'étude (test vs relecture)", "Investissement passé", "Congruence flanker"],
    "iv_levels": ["Congruent | Incongruent | Neutre", "1-back | 2-back | 3-back", "Valide (80%) | Invalide (20%)",
                  "Gains | Pertes", "Étudiés | Leurre | Neufs", "Seul | 1 autre | 4 autres", "10 | 65",
                  "Menaçant | Neutre | Positif", "0 | 1 | 2 | 5 | 10 | 25", "Test | Relecture", "Faible | Élevé",
                  "Congruent | Incongruent"],
    "dv": ["Temps de réaction (ms)", "Taux d'erreurs (%)", "d-prime (sensibilité)", "Taux de conformité (%)",
           "Confiance (0-100%)", "Choix binaire (sûr/risqué)", "Score OCEAN (1-7)", "Nombre de détections",
           "Liking (1-7)", "Rappel (%)", "Latence d'aide (ms)"],
    "dv_measure": ["Chronométrage automatique par essai (précision ms)", "Comptage des réponses correctes / essais",
                   "d' = z(hits) - z(fausses alertes)", "Proportion par condition d'essais critiques",
                   "Gamma de Goodman-Kruskal (calibration)", "Distribution des choix par cadrage",
                   "Moyenne des items Likert (inversés traités)", "Corrélation rang Spearman (fréquence-liking)"],
    "design": ["Intra-sujet (mesures répétées)", "Inter-sujets (groupes indépendants)", "Plan mixte (intra + inter)",
               "Contrebalancé (Latin square)", "Double aveugle", "Quasi-expérimental"],
    "population": ["Adultes (18-30)", "Étudiants", "Enfants (5-7 ans)", "Enfants (8-12 ans)", "Adolescents",
                   "Seniors (65+)", "Population clinique (anxiété)", "Population générale (panel en ligne)"],
    "n": ["30", "40", "50", "60", "80", "100", "120", "200"],
    "material": ["Écran + clavier", "Écran + casque audio", "PsyToolkit / PsychoPy", "Questionnaire papier",
                 "Application mobile", "EEG (32 canaux)", "Eye-tracker", "Tablette tactile"],
    "procedure": ["Instructions → entraînement → blocs expérimentaux randomisés → débriefing",
                  "Étude → distracteur → test → débriefing", "Pré-test → intervention → post-test",
                  "Scénarios randomisés → choix → débriefing des deux versions",
                  "Histoire illustrée → questions de compréhension → question clé",
                  "Présentations séquentielles chronométrées → phase d'évaluation"],
    "controls": ["Randomisation de l'ordre des essais", "Contrebalancement des conditions", "Luminance équilibrée entre stimuli",
                 "Timing constant (ISI fixe)", "Contrebalancement gauche/droite", "Double aveugle (expérimentateur)",
                 "Tâche distractrice entre phases", "Ordre de passage randomisé"],
    "ethics": ["Consentement éclairé, anonymat, droit de retrait", "Consentement parental (mineurs) + assentiment enfant",
               "Débriefing complet (biais révélé)", "Aucune donnée nominative, RGPD", "Validation par un comité d'éthique"],
    "expected": ["Effet Stroop classique : +60-120 ms en incongruent", "d' 2-back ≈ 1.5-2.5 chez l'adulte jeune",
                 "Conformité ≈ 30-37% des essais critiques (Asch 1951)",
                 "~72% de choix sûr en gains vs ~22% en pertes (K&T 1981)",
                 "Faux souvenir du leurre ≈ 60-80%", "Surconfiance typique : confiance - performance ≈ +10-20 points",
                 "Corrélation fréquence-liking ρ ≈ 0.5-0.8", "Avantage du test ≈ +15-30% au rappel final"],
    "analysis_plan": ["t-test apparié + d de Cohen", "ANOVA mesures répétées + Bonferroni", "Chi² d'indépendance + V de Cramér",
                      "Régression logistique (choix ~ condition)", "Facteur de Bayes BF10", "Corrélation Spearman + IC bootstrap",
                      "Mann-Whitney U (si non-normalité)", "ANOVA 2 facteurs + interaction"],
    "concepts": ["Charge cognitive", "Contrôle attentionnel", "Conformité", "Prospect theory", "Métacognition",
                 "Faux souvenirs", "Ancrage", "Diffusion de responsabilité", "Exposition (Zajonc)",
                 "Big Five", "Théorie de l'esprit", "Conservation piagétienne", "Testing effect", "Répétition espacée"],
}

def get_templates():
    return TEMPLATES

def get_suggestions():
    return SUGGESTIONS
