"""Fiches detaillees pour tous les concepts, outils et biais."""

DETAILS = {
    "c_conditionnement_classique": {
        "diagram": "/static/illustrations/diagram_conditioning_classical.jpg",
        "author_name": "Ivan Pavlov",
        "author_years": "1849-1936",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ivan_Pavlov_by_Mikhail_Nesterov_%281930%29.jpg/440px-Ivan_Pavlov_by_Mikhail_Nesterov_%281930%29.jpg",
        "doi": "10.1126/science.58.1496.359",
        "seminal_paper": "Pavlov, I.P. (1927). Conditioned Reflexes. Oxford University Press.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_conditionnement_operant", "c_dissonance"],
        "history": "Ivan Pavlov (1849-1936), physiologiste russe, decouvre le conditionnement classique par hasard en etudiant la digestion des chiens. Il remarque que les chiens salivent avant meme de recevoir la nourriture, des qu'ils entendent les pas de l'experimentateur. Cette observation fortuite mene a des experiences systematiques (1897-1903) ou un metronome ou une cloche est associe a la presentation de nourriture. Prix Nobel de physiologie en 1904.",
        "mechanisms": ["Association stimulus neutre + stimulus inconditionnel -> reponse conditionnee", "Extinction : presentation repetee du SC sans SI -> disparition de la RC", "Recuperation spontanee : la RC peut reapparaitre apres une periode de repos", "Generalisation : des stimuli similaires au SC provoquent aussi la RC", "Discrimination : apprentissage a distinguer le SC d'autres stimuli"],
        "key_experiments": [{"name": "Pavlov (1897)", "desc": "Chiens : cloche (SC) + nourriture (SI) -> salivation a la cloche seule (RC). 10-20 associations suffisent."}, {"name": "Watson & Rayner - Little Albert (1920)", "desc": "Conditionnement de la peur chez un bebe : rat blanc (SC) + bruit fort (SI) -> peur du rat (RC). Generalisation aux objets poilus."}, {"name": "Garcia & Koelling - Aversion gustative (1966)", "desc": "Les rats associent gout + nausee en un seul essai. L'association est selective : gout-nausee mais pas son-nausee."}],
        "real_world": [{"domain": "Marketing", "desc": "Association d'une marque (SC) avec des emotions positives (musique, celebrites) pour creer une preference conditionnee."}, {"domain": "Phobies", "desc": "Beaucoup de phobies resultent d'un conditionnement classique : morsure de chien -> peur des chiens. La therapie d'exposition utilise l'extinction."}, {"domain": "Addiction", "desc": "Les indices environnementaux associes a la consommation de drogue deviennent des SC qui declenchent le craving (RC)."}, {"domain": "Education", "desc": "Un eleve associe a une humiliation en classe (SI) peut developper une aversion conditionnee pour la matiere (RC)."}],
        "debiasing": ["Extinction par exposition repetee au SC sans SI", "Contre-conditionnement : associer le SC a un nouveau SI positif", "Desensibilisation systematique (Wolpe) : exposition graduelle en etat de relaxation"],
        "key_results": {"figure_desc": "Courbe d'acquisition : augmentation du nombre de reponses conditionnees au fil des essais, puis plateau. Courbe d'extinction : diminution progressive sans SI.", "stats": "Apres 10-20 essais d'association, la RC apparait dans 80-90% des cas. L'extinction necessite 20-50 essais sans SI."}
    },
    "c_conditionnement_operant": {
        "diagram": "/static/illustrations/diagram_conditioning_operant.jpg",
        "author_name": "B.F. Skinner",
        "author_years": "1904-1990",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/B.F._Skinner_at_Harvard_circa_1950.jpg/440px-B.F._Skinner_at_Harvard_circa_1950.jpg",
        "doi": "10.1037/11752-000",
        "seminal_paper": "Skinner, B.F. (1938). The Behavior of Organisms. Appleton-Century-Crofts.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_conditionnement_classique"],
        "history": "Edward Thorndike (1898) decouvre la 'loi de l'effet' avec ses puzzle boxes : les chats apprennent a s'echapper plus vite quand l'action est suivie d'une recompense. B.F. Skinner (1938) formalise le conditionnement operant avec sa Skinner Box, distinguant renforcement positif, renforcement negatif, punition positive et punition negative.",
        "mechanisms": ["Renforcement positif : ajout d'un stimulus agreable -> augmentation du comportement", "Renforcement negatif : retrait d'un stimulus desagreable -> augmentation du comportement", "Punition positive : ajout d'un stimulus desagreable -> diminution du comportement", "Punition negative : retrait d'un stimulus agreable -> diminution du comportement", "Programmes de renforcement : continu vs intermittent (ratio/interval, fixe/variable)"],
        "key_experiments": [{"name": "Thorndike - Puzzle Box (1898)", "desc": "Chats apprennent a tirer un levier pour s'echapper. Courbe d'apprentissage : temps de latence decroissant."}, {"name": "Skinner - Skinner Box (1938)", "desc": "Rats/pigeons appuient sur un levier pour recevoir de la nourriture. Le ratio variable produit le taux de reponse le plus eleve."}, {"name": "Ferster & Skinner (1957)", "desc": "Schedules of Reinforcement : etude systematique de tous les programmes de renforcement."}],
        "real_world": [{"domain": "Education", "desc": "Points, badges, classements = renforcement positif. Le feedback immediat est plus efficace que le feedback differe."}, {"domain": "Gamification", "desc": "Les notifications de reseaux sociaux utilisent le renforcement intermittent ratio variable - le plus addictif."}, {"domain": "Management", "desc": "Primes, promotions = renforcement positif. Le renforcement > punition pour changer les comportements."}],
        "debiasing": ["Privilegier le renforcement positif a la punition", "Utiliser le renforcement intermittent pour maintenir les comportements", "Extinction : ne plus renforcer le comportement indesirable"],
        "key_results": {"figure_desc": "Courbes cumulatives de Skinner : le ratio variable (VR) produit le taux de reponse le plus eleve et le plus resistant a l'extinction. Le ratio fixe (FR) produit un pattern 'pause post-renforcement'.", "stats": "VR-5 : ~2 reponses/seconde. FR-10 : ~1.5 rep/s avec pauses. VI-30s : ~0.5 rep/s. Extinction VR : 200+ reponses avant arret."}
    },
    "c_flow": {
        "diagram": "/static/illustrations/diagram_flow.jpg",
        "author_name": "Mihaly Csikszentmihalyi",
        "author_years": "1934-2021",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Mihaly_Csikszentmihalyi.jpg/440px-Mihaly_Csikszentmihalyi.jpg",
        "doi": "10.1037/0022-3514.72.4.815",
        "seminal_paper": "Csikszentmihalyi, M. (1990). Flow: The Psychology of Optimal Experience. Harper & Row.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_growth_mindset", "c_attachment"],
        "history": "Mihaly Csikszentmihalyi (1975) etudie d'abord le flow chez les artistes peintres, les chirurgiens et les joueurs d'echecs. Il identifie 8 conditions : equilibre defi/competence, fusion action/conscience, objectifs clairs, feedback immediat, concentration totale, sentiment de controle, perte de conscience de soi, distorsion du temps.",
        "mechanisms": ["Equilibre defi-competence : le defi doit etre legerement au-dessus du niveau de competence", "Fusion action-conscience : l'attention est entierement absorbee par la tache", "Objectifs clairs + feedback immediat", "Concentration totale : exclusion des distractions", "Perte de conscience de soi : immersion complete", "Distorsion temporelle : le temps semble passer plus vite"],
        "key_experiments": [{"name": "Csikszentmihalyi (1975)", "desc": "Interviews de 500+ personnes. Identification des 8 dimensions du flow."}, {"name": "Nakamura & Csikszentmihalyi (2002)", "desc": "Revue complete : le flow est universel et correle avec performance et bien-etre."}, {"name": "Engeser & Rheinberg (2008)", "desc": "Le flow est optimal quand defi percu = competence percue."}],
        "real_world": [{"domain": "Jeux video", "desc": "Difficulte adaptative, objectifs clairs, feedback constant pour maintenir le joueur dans le flow."}, {"domain": "Programmation", "desc": "Le 'coding flow' : etat productif ou les developpeurs ecrivent du code complexe pendant des heures."}, {"domain": "Sport", "desc": "'Being in the zone' : performance automatique, absence de pensee consciente."}, {"domain": "Education", "desc": "Taches dans la ZPD de Vygotsky = zone de flow de Csikszentmihalyi."}],
        "debiasing": ["Equilibrer defi et competence", "Objectifs clairs + feedback immediat", "Eliminer les distractions", "Sessions de 90 minutes"],
        "key_results": {"figure_desc": "Modele 2D defi x competence : zone de flow sur la diagonale, anxiété en haut a gauche, ennui en bas a droite, apathie en bas a gauche.", "stats": "Le flow est correle avec performance (r=0.3-0.5), creativite (r=0.4), bien-etre (r=0.5). Duree moyenne d'un episode : 30-120 minutes."}
    },
    "c_attachment": {
        "diagram": "/static/illustrations/diagram_attachment.jpg",
        "author_name": "John Bowlby & Mary Ainsworth",
        "author_years": "1907-1990 / 1913-1999",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/John_Bowlby.jpg/440px-John_Bowlby.jpg",
        "doi": "10.1037/0022-3514.54.3.511",
        "seminal_paper": "Bowlby, J. (1969). Attachment and Loss, Vol. 1. Basic Books. / Ainsworth, M.D.S. et al. (1978). Patterns of Attachment. Erlbaum.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_flow", "c_resilience"],
        "history": "John Bowlby (1958-1980) developpe la theorie de l'attachement en observant les enfants separes de leurs parents pendant la Seconde Guerre mondiale. Mary Ainsworth (1978) cree la 'Strange Situation' pour classifier les styles : securise (~60%), anxieux (~15%), evitant (~20%), desorganise (~5%).",
        "mechanisms": ["Base securise : le caregiver fournit un refuge en cas de menace et une base pour explorer", "Modeles internes operants : representations mentales de soi et des autres", "Styles : securise (confiance), anxieux (peur d'abandon), evitant (autosuffisance)", "Transmission intergenerationnelle des styles", "Plasticite : les styles peuvent evoluer"],
        "key_experiments": [{"name": "Ainsworth - Strange Situation (1978)", "desc": "8 episodes separation/reunion. Classification en 3 styles d'attachement."}, {"name": "Harlow - Singes rhesus (1958)", "desc": "Bebe singes preferent mere en tissu doux sans nourriture a mere en fil de fer avec biberon."}, {"name": "Hazan & Shaver (1987)", "desc": "Styles d'attachement infantile retrouves dans les relations amoureuses adultes."}],
        "real_world": [{"domain": "Relations amoureuses", "desc": "Anxieux cherchent proximite, evitants fuient l'intimite. Couples anxieux-evitant frequents mais conflictuels."}, {"domain": "Management", "desc": "Leaders 'base securise' favorisent exploration et innovation."}, {"domain": "Therapie", "desc": "Relation therapeute-patient = experience d'attachement corrective."}, {"domain": "Education", "desc": "Enseignants 'base securise' favorisent l'exploration cognitive."}],
        "debiasing": ["Therapie d'attachement (EFT, psychodynamique)", "Relations correctives", "Earned security : attachement securise peut s'acquerir a l'age adulte"],
        "key_results": {"figure_desc": "Distribution des styles : Securise 60%, Evitant 20%, Anxieux 15%, Desorganise 5%. Correlations : securise -> satisfaction relationnelle (r=0.4), anxieux -> jalousie (r=0.5).", "stats": "Stabilite des styles sur 20 ans : r=0.4-0.5. Transmission parent-enfant : 75% de concordance. Earned security : ~30% des insécures deviennent sécures."}
    },
    "c_resilience": {
        "diagram": None,
        "author_name": "Michael Rutter & Boris Cyrulnik",
        "author_years": "1933- / 1937-",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Boris_Cyrulnik_2011.jpg/440px-Boris_Cyrulnik_2011.jpg",
        "doi": "10.1017/S0954579400005889",
        "seminal_paper": "Rutter, M. (1987). Psychosocial resilience and protective mechanisms. American Journal of Orthopsychiatry.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_attachment"],
        "history": "Michael Rutter (1979) etudie les enfants de l'ile de Wight et identifie les facteurs protecteurs. Emmy Werner (1989) suit 698 enfants de Kauai de la naissance a 40 ans. Boris Cyrulnik popularise le concept en France avec 'Un merveilleux malheur' (1999).",
        "mechanisms": ["Facteurs individuels : temperament facile, intelligence, estime de soi", "Facteurs familiaux : au moins un adulte bienveillant, cohesion familiale", "Facteurs communautaires : ecole, mentors, activites valorisantes", "Processus : coping actif, reinterpretation positive, recherche de soutien", "Neurobiologie : plasticite cerebrale, regulation du stress (axe HPA)"],
        "key_experiments": [{"name": "Rutter - Ile de Wight (1979)", "desc": "Etude epidemiologique de 2000+ enfants. Facteurs de risque et protecteurs."}, {"name": "Werner - Kauai (1989)", "desc": "Etude longitudinale de 698 enfants sur 40 ans. 1/3 resilients malgre adversite."}, {"name": "Masten (2001)", "desc": "Ordinary Magic : la resilience n'est pas extraordinaire mais repose sur des processus normaux."}],
        "real_world": [{"domain": "Education", "desc": "Programmes de mentorat pour enfants defavorises. Un adulte bienveillant = facteur protecteur majeur."}, {"domain": "Clinique", "desc": "Therapie centre sur les ressources plutot que les deficits. Narration de resilience."}, {"domain": "Organisations", "desc": "Resilience organisationnelle : capacite a rebondir apres une crise."}],
        "debiasing": ["Renforcer les facteurs protecteurs plutot que reduire les facteurs de risque", "Au moins un adulte bienveillant = facteur le plus puissant", "La resilience est un processus, pas un trait"],
        "key_results": {"figure_desc": "Modele ecologique de la resilience : individu au centre, entoure de couches (famille, ecole, communaute, culture).", "stats": "1/3 des enfants a haut risque deviennent resilients. Facteur protecteur #1 : un adulte bienveillant (OR=3.5). Correlation resilience-bien-etre : r=0.5."}
    },
    "c_growth_mindset": {
        "diagram": None,
        "author_name": "Carol Dweck",
        "author_years": "1946-",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Carol_Dweck.jpg/440px-Carol_Dweck.jpg",
        "doi": "10.1037/0033-295X.95.2.256",
        "seminal_paper": "Dweck, C.S. (2006). Mindset: The New Psychology of Success. Random House.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_flow"],
        "history": "Carol Dweck (1988) identifie les theories implicites de l'intelligence : fixe vs mallable. Mueller & Dweck (1998) montrent que les enfants loues pour l'effort persistent plus. Le best-seller 'Mindset' (2006) popularise le concept. Meta-analyse de Sisk (2018) : effet modeste (d=0.10).",
        "mechanisms": ["Fixed mindset : l'intelligence est un trait fixe. L'echec = preuve d'incompetence.", "Growth mindset : l'intelligence est mallable. L'echec = opportunite d'apprentissage.", "Feedback sur l'effort vs le talent : effets opposés sur la persistance", "Neuroplasticite comme base biologique du growth mindset", "Interventions breves mais puissantes (30 min)"],
        "key_experiments": [{"name": "Mueller & Dweck (1998)", "desc": "Enfants loues pour l'effort persistent plus et choisissent des taches difficiles. Loues pour l'intelligence : evitement du defi."}, {"name": "Yeager et al. (2019) - Nature", "desc": "Etude sur 12 000 eleves americains. Intervention de 30 min ameliore les notes des eleves en difficulte."}, {"name": "Sisk et al. (2018) - Meta-analyse", "desc": "Effet modeste (d=0.10). Plus fort pour les eleves a risque et les matieres academiques."}],
        "real_world": [{"domain": "Education", "desc": "Louer l'effort et la strategie, pas le talent. 'Tu as bien travaille' vs 'Tu es intelligent'."}, {"domain": "Management", "desc": "Culture d'entreprise growth mindset : l'echec est une opportunite d'apprentissage."}, {"domain": "Sport", "desc": "Les athletes growth mindset s'entrainent plus et rebondissent mieux apres les defaites."}],
        "debiasing": ["Louer le processus (effort, strategie) pas la personne", "Presenter l'echec comme information, pas comme verdict", "Intervention breve mais repetee (pas one-shot)"],
        "key_results": {"figure_desc": "Mueller & Dweck (1998) : apres echec, les enfants 'effort' choisissent 67% de taches difficiles vs 8% pour les enfants 'intelligence'.", "stats": "Meta-analyse Sisk (2018) : d=0.10 global, d=0.19 pour eleves a risque. Yeager (2019) : +0.1 GPA pour eleves en difficulte (N=12 490)."}
    },
    "c_dissonance": {
        "diagram": None,
        "author_name": "Leon Festinger",
        "author_years": "1919-1989",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Leon_Festinger.jpg/440px-Leon_Festinger.jpg",
        "doi": "10.1037/h0042879",
        "seminal_paper": "Festinger, L. (1957). A Theory of Cognitive Dissonance. Stanford University Press.",
        "simulation_template": "framing",
        "lab_tools": ["tmpl_framing"],
        "related_concepts_ids": ["b_sunk_cost", "b_auto_complaisance"],
        "history": "Leon Festinger (1957) publie la theorie de la dissonance cognitive. L'experience $1/$20 (Festinger & Carlsmith, 1959) montre le resultat contre-intuitif : faible recompense -> plus grand changement d'attitude.",
        "mechanisms": ["Inconfort psychologique quand action ≠ croyance", "Reduction de la dissonance : changer l'attitude, changer l'action, ou rationaliser", "Effet de la justification insuffisante : moins de justification externe -> plus de changement interne", "Auto-perception (Bem) : on infer nos attitudes de nos comportements", "Dissonance post-decision : justification du choix apres la decision"],
        "key_experiments": [{"name": "Festinger & Carlsmith (1959) - $1/$20", "desc": "Tache ennuyeuse -> dire que c'etait interessant. $1 -> changement d'attitude. $20 -> pas de changement (justification externe suffisante)."}, {"name": "Aronson & Mills (1959) - Initiation", "desc": "Initiation difficile -> plus grande valorisation du groupe (justification de l'effort)."}, {"name": "Brehm (1956) - Choix", "desc": "Apres un choix difficile, on augmente la valeur de l'option choisie et diminue celle de l'option rejetee."}],
        "real_world": [{"domain": "Marketing", "desc": "Techniques d'engagement : petit engagement initial -> plus grand engagement ulterieur (pied dans la porte)."}, {"domain": "Politique", "desc": "Les militants qui investissent du temps/argent rationalisent leur engagement en renforcant leurs convictions."}, {"domain": "Sante", "desc": "Les fumeurs minimisent les risques pour reduire la dissonance entre comportement et connaissance."}],
        "debiasing": ["Conscientiser la dissonance plutot que la reduire automatiquement", "Accepter l'inconfort comme signal d'incoherence", "Prendre du temps avant de rationaliser"],
        "key_results": {"figure_desc": "Festinger & Carlsmith (1959) : condition $1 -> evaluation 3.63/6. Condition $20 -> evaluation 2.50/6. Controle -> 2.00/6.", "stats": "Effet de la justification insuffisante : d=0.81 (meta-analyse). Plus fort quand le comportement est librement choisi et public."}
    },

    # ═══ OUTILS ═══
    "o_stroop": {
        "diagram": "/static/illustrations/diagram_stroop.jpg",
        "author_name": "John Ridley Stroop",
        "author_years": "1897-1973",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Stroop_effect.png/440px-Stroop_effect.png",
        "doi": "10.1037/h0054651",
        "seminal_paper": "Stroop, J.R. (1935). Studies of interference in serial verbal reactions. JEP, 18(6), 643-662.",
        "simulation_template": "stroop",
        "lab_tools": ["tmpl_stroop"],
        "related_concepts_ids": ["c_conditionnement_classique"],
        "history": "John Ridley Stroop (1935) publie 'Studies of Interference in Serial Verbal Reactions'. 3 experiences avec 70, 100 et 240 participants. L'effet Stroop devient le test le plus utilise en psychologie cognitive (18 000+ citations).",
        "how_to_use": "1. Presenter des mots de couleurs imprimes en encre congruente (ROUGE en rouge) ou incongruente (ROUGE en bleu).\n2. Le participant nomme la COULEUR D'ENCRE le plus vite possible.\n3. Chronometrer le temps de reponse par condition.\n4. Calculer l'effet Stroop = TR incongruent - TR congruent.\n5. Un effet > 200ms est typique.",
        "advantages": ["Simple a administrer (5 minutes)", "Effet robuste et reproductible (d > 1.0)", "Sensible aux dysfonctions executives", "Nombreuses variantes", "Disponible en ligne (PsyToolkit)"],
        "limitations": ["Ne mesure qu'un aspect du controle executif", "Sensible a la pratique", "Influence par la fatigue et l'age", "Pas de norme universelle"],
        "real_world": [{"domain": "Clinique", "desc": "Diagnostic TDAH, lesions frontales, schizophrenie, demence."}, {"domain": "Recherche", "desc": "Paradigme standard pour l'attention selective et le controle inhibiteur."}, {"domain": "Stroop emotionnel", "desc": "Variante avec mots emotionnels : les anxieux sont ralentis par les mots menacants."}],
        "key_results": {"figure_desc": "3 conditions : Congruent (~600ms), Neutre (~650ms), Incongruent (~800ms). Effet Stroop = 200ms. Accuracy > 95% sauf incongruent (~85%).", "stats": "Effet Stroop moyen : 200ms (IC95% [180-220]). d de Cohen = 1.2 (effet large). Test-retest r = 0.85."}
    },
    "o_big_five": {
        "diagram": "/static/illustrations/diagram_bigfive.jpg",
        "author_name": "Costa & McCrae",
        "author_years": "1940- / 1940-",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Big_Five_personality_traits.png/440px-Big_Five_personality_traits.png",
        "doi": "10.1037/0022-3514.63.5.849",
        "seminal_paper": "Costa, P.T. & McCrae, R.R. (1992). Revised NEO Personality Inventory (NEO-PI-R). PAR.",
        "simulation_template": "bigfive",
        "lab_tools": ["tmpl_bigfive"],
        "related_concepts_ids": [],
        "history": "Lewis Goldberg (1981) identifie les 5 facteurs par analyse lexicale. Costa & McCrae (1992) developpent le NEO-PI-R (240 items). Gosling et al. (2003) creent le TIPI (10 items, 1 minute). Le Big Five est le modele de personnalite le plus valide empiriquement.",
        "how_to_use": "1. Administrer le questionnaire (NEO-PI-R : 240 items ; TIPI : 10 items ; IPIP-NEO : 120 items, gratuit).\n2. Calculer les scores sur 5 dimensions : O, C, E, A, N.\n3. Comparer aux normes populationnelles.\n4. Interpreter : C eleve = performance, N eleve = vulnerabilite stress, O eleve = creativite.",
        "advantages": ["Validite empirique robuste", "Stabilite temporelle (r ~ 0.7 sur 10 ans)", "Universalite culturelle (50+ cultures)", "Predicteur de performance professionnelle", "Version courte disponible (TIPI)"],
        "limitations": ["Auto-rapporte = biais de desirabilite sociale", "Ne capture pas toute la personnalite", "Variations culturelles", "Pas de 'bon' ou 'mauvais' profil"],
        "real_world": [{"domain": "Recrutement", "desc": "Conscienciosite = meilleur predicteur de performance (r ~ 0.2-0.3)."}, {"domain": "Orientation", "desc": "Matching personnalite-metier."}, {"domain": "Recherche", "desc": "Variable de controle dans des milliers d'etudes."}],
        "key_results": {"figure_desc": "Distribution normale des 5 traits (moyenne=50, ET=10). Correlations inter-traits faibles (|r|<0.3). Heritabilite : 40-60%.", "stats": "Conscienciosite -> performance travail : r=0.22. Neuroticisme -> satisfaction vie : r=-0.35. Ouverture -> creativite : r=0.30."}
    },
    "o_irmf": {
        "diagram": "/static/illustrations/diagram_fmri.jpg",
        "author_name": "Seiji Ogawa",
        "author_years": "1934-",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/FMRI_scan.jpg/440px-FMRI_scan.jpg",
        "doi": "10.1002/mrm.1910140207",
        "seminal_paper": "Ogawa, S. et al. (1990). Brain magnetic resonance imaging with contrast dependent on blood oxygenation. PNAS.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_eeg"],
        "history": "Seiji Ogawa (1990) decouvre que le signal IRM est sensible a l'oxygeneation du sang (signal BOLD). Kwong et al. (1992) realisent la premiere carte d'activation cerebrale fonctionnelle chez l'humain.",
        "how_to_use": "1. Placer le participant dans le scanner (1.5T a 7T).\n2. Alterner tache et repos (design par blocs ou eventiel).\n3. Acquerir des volumes toutes les 2-3 secondes.\n4. Pretraitement : correction mouvement, normalisation, lissage.\n5. Analyse statistique : GLM voxel par voxel.\n6. Seuillage et correction comparaisons multiples.",
        "advantages": ["Resolution spatiale excellente (1-3mm)", "Non invasif", "Couverture cerebrale complete", "Compatible avec nombreuses taches"],
        "limitations": ["Resolution temporelle faible (~2s)", "Signal BOLD = mesure indirecte", "Correlationnel, pas causal", "Cout eleve (500-1000 euros/session)"],
        "real_world": [{"domain": "Recherche cognitive", "desc": "Cartographie des fonctions : attention, memoire, langage."}, {"domain": "Clinique", "desc": "Cartographie pre-chirurgicale. Diagnostic differentiel."}, {"domain": "Neuroeconomie", "desc": "Bases neurales de la decision."}],
        "key_results": {"figure_desc": "Carte d'activation cerebrale : zones colorees (rouge/jaune = activation, bleu = desactivation) superposees sur anatomie.", "stats": "Resolution spatiale : 1-3mm. Resolution temporelle : TR=2s. Signal BOLD : pic 5-6s post-stimulus. Effet typique : 1-5% de changement de signal."}
    },
    "o_eeg": {
        "diagram": "/static/illustrations/diagram_eeg.jpg",
        "author_name": "Hans Berger",
        "author_years": "1873-1941",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hans_Berger_1930.jpg/440px-Hans_Berger_1930.jpg",
        "doi": "10.1007/BF01797193",
        "seminal_paper": "Berger, H. (1929). Uber das Elektrenkephalogramm des Menschen. Archiv fur Psychiatrie.",
        "simulation_template": "oddball",
        "lab_tools": ["tmpl_p300"],
        "related_concepts_ids": ["o_irmf"],
        "history": "Hans Berger (1924) enregistre le premier EEG humain. Il decouvre le rythme alpha (8-12 Hz). Les potentiels evoques (ERP) sont identifies dans les annees 1960 : P300 (Donchin, 1967), N400 (Kutas & Hillyard, 1980).",
        "how_to_use": "1. Placer le casque EEG (32, 64 ou 128 electrodes).\n2. Appliquer le gel conducteur.\n3. Verifier les impedances (< 5 kOhm).\n4. Presenter les stimuli et enregistrer.\n5. Pretraitement : filtrage, rejet artefacts, segmentation.\n6. Moyennage pour obtenir les ERP.\n7. Analyse : amplitude et latence des composantes.",
        "advantages": ["Resolution temporelle excellente (~1ms)", "Portable et peu couteux", "Compatible avec populations variees", "Mesure directe de l'activite neuronale"],
        "limitations": ["Resolution spatiale faible", "Sensible aux artefacts", "Ne detecte que l'activite corticale superficielle", "Analyse complexe"],
        "real_world": [{"domain": "Recherche cognitive", "desc": "ERP : P300, N400, ERN. Oscillations : alpha, gamma, theta."}, {"domain": "Clinique", "desc": "Diagnostic epilepsie. Monitoring sommeil. Evaluation conscience."}, {"domain": "BCI", "desc": "Interfaces cerveau-machine pour patients paralyses."}],
        "key_results": {"figure_desc": "Traces ERP : P300 (positif, ~300ms, Pz), N400 (negatif, ~400ms, centro-parietal). Spectre de puissance : alpha 8-12Hz dominant au repos yeux fermes.", "stats": "P300 : amplitude 10-20μV, latence 300-500ms. N400 : -5 a -10μV, latence 350-450ms. Alpha : 20-50μV yeux fermes."}
    },
    "o_nback": {
        "diagram": "/static/illustrations/diagram_nback.jpg",
        "author_name": "Kirchner",
        "author_years": "1958",
        "author_image": None,
        "doi": "10.1037/h0042648",
        "seminal_paper": "Kirchner, W.K. (1958). Age differences in short-term retention of rapidly changing information. JEP.",
        "simulation_template": "nback",
        "lab_tools": ["tmpl_nback"],
        "related_concepts_ids": [],
        "history": "Kirchner (1958) introduit la tache N-back pour mesurer la memoire de travail. Cohen et al. (1994) l'adaptent pour l'IRMf. Jaeggi et al. (2008) publient une etude controversee affirmant que le dual n-back augmente l'intelligence fluide.",
        "how_to_use": "1. Presenter des stimuli un par un (500ms, ISI 2500ms).\n2. Appuyer quand stimulus actuel = celui N positions en arriere.\n3. Commencer par 1-back, puis 2-back, 3-back.\n4. Mesurer : hits, false alarms, d-prime.\n5. Un d-prime > 2 en 2-back est typique.",
        "advantages": ["Mesure directe de la mise a jour", "Parametre N ajustable", "Compatible IRMf et EEG", "Disponible en ligne"],
        "limitations": ["Validite construit debattue (Huang 2025)", "Strategies de chunking possibles", "L'entrainement ne transfere pas a l'intelligence generale"],
        "real_world": [{"domain": "Recherche WMC", "desc": "Mesure standard de la mise a jour. Correlee avec intelligence fluide."}, {"domain": "Entrainement cognitif", "desc": "Dual n-back dans les programmes d'entrainement. Efficacite controversee."}, {"domain": "Clinique", "desc": "Evaluation TDAH, schizophrenie, lesions prefrontales."}],
        "key_results": {"figure_desc": "Performance en fonction de N : d-prime decroit de ~3.5 (1-back) a ~2.5 (2-back) a ~1.5 (3-back). TR augmente avec N.", "stats": "2-back : d'=2.5 (ET=0.8), TR=600ms (ET=150). 3-back : d'=1.5 (ET=0.9), TR=750ms (ET=200). Correlation avec gF : r=0.3-0.5."}
    },
    "o_wais": {
        "diagram": "/static/illustrations/diagram_wais.jpg",
        "author_name": "David Wechsler",
        "author_years": "1896-1981",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/David_Wechsler_1949.jpg/440px-David_Wechsler_1949.jpg",
        "doi": "10.1037/t15169-000",
        "seminal_paper": "Wechsler, D. (2008). WAIS-IV Technical and Interpretive Manual. Pearson.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "David Wechsler (1955) publie la premiere WAIS pour adultes. La 4e edition (2008) comprend 4 indices : Comprehension verbale, Raisonnement perceptif, Memoire de travail, Vitesse de traitement. C'est le test de QI le plus utilise au monde.",
        "how_to_use": "1. Administration individuelle par un psychologue forme (60-90 min).\n2. 10 sous-tests principaux + 5 supplementaires.\n3. Calcul des 4 indices et du QI total.\n4. Comparaison aux normes (moyenne=100, ET=15).\n5. Analyse du profil : forces et faiblesses relatives.",
        "advantages": ["Standard international de reference", "Validite et fidelite excellentes", "Normes francaises actualisees", "Detecte deficience intellectuelle et HP"],
        "limitations": ["Administration longue (60-90 min)", "Necessite un psychologue forme", "Biais culturels possibles", "Cout eleve"],
        "real_world": [{"domain": "Clinique", "desc": "Diagnostic deficience intellectuelle (QI < 70) ou haut potentiel (QI > 130)."}, {"domain": "Neuropsychologie", "desc": "Evaluation des troubles cognitifs post-AVC, demence, TDAH."}, {"domain": "Orientation", "desc": "Profil cognitif pour l'orientation scolaire et professionnelle."}],
        "key_results": {"figure_desc": "Distribution normale du QI : moyenne=100, ET=15. 68% entre 85-115, 95% entre 70-130. 4 indices : ICV, IRP, IMT, IVT.", "stats": "Fidelite test-retest : r=0.93 (QI total). Validite predictive : QI -> performance scolaire r=0.5. Effet Flynn : +3 points/decennie (1930-2000)."}
    },
    "o_prisma": {
        "diagram": None,
        "author_name": "Moher et al.",
        "author_years": "2009",
        "author_image": None,
        "doi": "10.1371/journal.pmed.1000097",
        "seminal_paper": "Moher, D. et al. (2009). Preferred reporting items for systematic reviews and meta-analyses: the PRISMA statement. PLoS Medicine.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "Moher et al. (2009) publient la declaration PRISMA avec une checklist de 27 items et un diagramme de flux. Page et al. (2021) publient PRISMA 2020. Standard de reporting adopte par la majorite des revues scientifiques.",
        "how_to_use": "1. Enregistrer le protocole (PROSPERO).\n2. Suivre la checklist PRISMA 2020 (27 items).\n3. Diagramme de flux : identifier -> screen -> eligibilite -> inclusion.\n4. Evaluer le risque de biais (ROB 2, ROBINS-I).\n5. Synthese narrative et/ou meta-analyse.\n6. Rapport GRADE pour la certitude des preuves.",
        "advantages": ["Standard international reconnu", "Ameliore transparence et reproductibilite", "Checklist structuree (27 items)", "Diagramme de flux visuel"],
        "limitations": ["PRISMA = qualite du REPORTING, pas de la revue", "Adhesion variable", "Ne garantit pas l'absence de biais"],
        "real_world": [{"domain": "Medecine", "desc": "Revues Cochrane suivent PRISMA. Guidelines cliniques (HAS, NICE)."}, {"domain": "Psychologie", "desc": "Standard pour les meta-analyses."}, {"domain": "Education", "desc": "Revue des interventions educatives."}],
        "key_results": {"figure_desc": "Diagramme de flux PRISMA : Identification (n=X) -> Screening (n=Y) -> Eligibilite (n=Z) -> Inclusion (n=W).", "stats": "Adoption PRISMA : 73% des revues medicales (2020). Qualite reporting : score moyen 18/27 items. Impact : meilleures revues = meilleur impact factor."}
    },
    "o_mai": {
        "diagram": None,
        "author_name": "Schraw & Dennison",
        "author_years": "1994",
        "author_image": None,
        "doi": "10.1006/ceps.1994.1006",
        "seminal_paper": "Schraw, G. & Dennison, R.S. (1994). Assessing metacognitive awareness. Contemporary Educational Psychology.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "Schraw & Dennison (1994) developpent le MAI avec 52 items mesurant 8 sous-echelles : connaissances declaratives, procedurales, conditionnelles, planification, monitoring, evaluation, debugging, gestion de l'information.",
        "how_to_use": "1. Administrer les 52 items (Likert 1-5).\n2. Calculer les scores par sous-echelle.\n3. Connaissances = declaratif + procedural + conditionnel.\n4. Regulation = planification + monitoring + evaluation + debugging + gestion.\n5. Score total = somme des 52 items (max 260).",
        "advantages": ["Validite de construit etablie", "52 items couvrent 2 dimensions", "Utilise dans des centaines d'etudes", "Gratuit et libre"],
        "limitations": ["Auto-rapporte = biais de desirabilite", "Correlation modeste avec performance reelle (r ~ 0.3)"],
        "real_world": [{"domain": "Education", "desc": "Evaluation des interventions metacognitives."}, {"domain": "Formation", "desc": "Predicteur de transfert des apprentissages."}],
        "key_results": {"figure_desc": "Structure factorielle : 2 facteurs (Connaissances + Regulation) expliquant 46% de la variance.", "stats": "Alpha de Cronbach : 0.90 (total). Correlation MAI-performance : r=0.30. Correlation MAI-SRL : r=0.55."}
    },
    "o_likert": {
        "diagram": None,
        "author_name": "Rensis Likert",
        "author_years": "1903-1981",
        "author_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Likert_Scale_example.png/440px-Likert_Scale_example.png",
        "doi": "10.1037/h0046961",
        "seminal_paper": "Likert, R. (1932). A technique for the measurement of attitudes. Archives of Psychology.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "Rensis Likert (1932) developpe l'echelle de reponse ordinale qui porte son nom. C'est l'outil de mesure le plus utilise en psychologie et en sciences sociales.",
        "how_to_use": "1. Definir l'objet de mesure (attitude, satisfaction, accord).\n2. Rediger des items clairs et unidimensionnels.\n3. Choisir le nombre de points (5 ou 7 le plus courant).\n4. Alterner items positifs et negatifs (eviter acquiescement).\n5. Calculer la moyenne ou la somme des scores.",
        "advantages": ["Simple a construire et administrer", "Universellement compris", "Compatible avec analyses statistiques paramatriques", "Adaptable a tout domaine"],
        "limitations": ["Biais de desirabilite sociale", "Tendance au point central", "Effet de l'ordre des items", "Debat : ordinale ou intervalle ?"],
        "real_world": [{"domain": "Satisfaction client", "desc": "1 a 5 etoiles. NPS (Net Promoter Score)."}, {"domain": "Recherche", "desc": "Mesure d'attitudes, opinions, perceptions dans des milliers d'etudes."}],
        "key_results": {"figure_desc": "Exemple d'echelle Likert 5 points : 1=Pas du tout d'accord, 2=Pas d'accord, 3=Neutre, 4=D'accord, 5=Tout a fait d'accord.", "stats": "5 points optimal pour la plupart des usages. 7 points pour plus de sensibilite. Alpha de Cronbach typique : 0.7-0.9."}
    },
    "o_iat": {
        "diagram": None,
        "author_name": "Greenwald, McGhee & Schwartz",
        "author_years": "1998",
        "author_image": None,
        "doi": "10.1037/0022-3514.74.6.1464",
        "seminal_paper": "Greenwald, A.G., McGhee, D.E. & Schwartz, J.L.K. (1998). Measuring individual differences in implicit cognition. JPSP.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["b_confirmation", "b_halo"],
        "history": "Greenwald, McGhee & Schwartz (1998) developpent le Test d'Association Implicite pour mesurer les associations automatiques entre concepts. Le Project Implicit (Harvard) l'a rendu accessible en ligne.",
        "how_to_use": "1. Le participant categorise rapidement des stimuli en 2 categories.\n2. Blocs compatibles (fleurs + positif / insectes + negatif).\n3. Blocs incompatibles (fleurs + negatif / insectes + positif).\n4. Mesurer la difference de temps de reponse (effet D).\n5. D > 0.65 = forte association implicite.",
        "advantages": ["Mesure des biais implicites (inconscients)", "Difficile a faker", "Disponible en ligne gratuitement", "Nombreuses variantes (race, genre, age)"],
        "limitations": ["Fiabilite test-retest modeste (r ~ 0.5)", "Validite predictive du comportement faible", "Interpretation delicate"],
        "real_world": [{"domain": "Formation diversite", "desc": "Prise de conscience des biais implicites en entreprise."}, {"domain": "Recherche", "desc": "Etude des prejudices implicites (race, genre, age)."}],
        "key_results": {"figure_desc": "Effet D = (M_incompatible - M_compatible) / SD_pool. Distribution : D=0 (pas de biais), D=0.2 (leger), D=0.5 (modere), D=0.8 (fort).", "stats": "Fiabilite test-retest : r=0.50. Validite predictive comportement : r=0.10-0.20. Prevalence biais implicite : 70-80% des participants."}
    },
    "o_ems": {
        "diagram": None,
        "author_name": "Vallerand et al.",
        "author_years": "1992",
        "author_image": None,
        "doi": "10.1037/0022-0663.84.3.378",
        "seminal_paper": "Vallerand, R.J. et al. (1992). The Academic Motivation Scale. Journal of Educational Psychology.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_autodetermination"],
        "history": "Vallerand et al. (1992) developpent l'Echelle de Motivation basee sur la theorie de l'autodetermination de Deci & Ryan.",
        "how_to_use": "1. Administrer les 28 items (Likert 1-7).\n2. Calculer les 7 sous-echelles : motivation intrinseque (3 types), extrinseque (3 types), amotivation.\n3. Profil motivationnel : dominance intrinseque vs extrinseque vs amotivation.",
        "advantages": ["Base theorique solide (TAD)", "7 sous-echelles couvrent le continuum motivationnel", "Valide en francais"],
        "limitations": ["Auto-rapporte", "Sensibilite au contexte"],
        "real_world": [{"domain": "Education", "desc": "Predicteur d'engagement et de perseverance."}, {"domain": "Sport", "desc": "Motivation intrinseque = performance et bien-etre."}],
        "key_results": {"figure_desc": "Continuum motivationnel : Amotivation -> Regulation externe -> Introjectee -> Identifiee -> Intrinseque.", "stats": "Alpha de Cronbach : 0.79-0.89 par sous-echelle. Motivation intrinseque -> persistance : r=0.45. Amotivation -> abandon : r=0.50."}
    },
    "o_reperes_bastien_scapin": {
        "diagram": None,
        "author_name": "Bastien & Scapin",
        "author_years": "1993",
        "author_image": None,
        "doi": "10.1016/0020-7373(93)90061-4",
        "seminal_paper": "Bastien, J.M.C. & Scapin, D.L. (1993). Ergonomic criteria for interactive systems. International Journal of Human-Computer Interaction.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["c_charge_cognitive"],
        "history": "Bastien & Scapin (1993, INRIA) developpent 8 criteres ergonomiques pour l'evaluation des interfaces homme-machine. 3500+ citations. Standard francophone en ergonomie IHM.",
        "how_to_use": "1. Evaluer l'interface sur les 8 criteres : guidage, charge de travail, controle explicite, adaptabilite, gestion des erreurs, coherence, signifiance des codes, compatibilite.\n2. Grille d'evaluation avec indicateurs pour chaque critere.\n3. Score par critere et score global.\n4. Recommandations d'amelioration.",
        "advantages": ["Standard francophone de reference", "8 criteres couvrent tous les aspects IHM", "Grille structuree et operationnelle", "Gratuit"],
        "limitations": ["Concu pour le desktop", "Adaptation mobile/VR necessaire", "Complementarite avec heuristiques de Nielsen"],
        "real_world": [{"domain": "Ergonomie IHM", "desc": "Evaluation et conception d'interfaces logicielles et web."}, {"domain": "UX Design", "desc": "Checklist pour les revues de design."}],
        "key_results": {"figure_desc": "8 criteres en radar chart : guidage, charge, controle, adaptabilite, erreurs, coherence, signifiance, compatibilite.", "stats": "Inter-evaluateurs : kappa=0.65-0.80. Correlation avec satisfaction utilisateur : r=0.55. Nombre moyen de problemes detectes : 15-30 par evaluation."}
    },
}

def get_concept_detail(concept_id):
    return DETAILS.get(concept_id)

def get_all_concept_details():
    return DETAILS

# ═══════════════════════════════════════════════════════════════════════════════
# OUTILS DE TRAITEMENT DE DONNÉES
# ═══════════════════════════════════════════════════════════════════════════════

DATA_PROCESSING_TOOLS = {
    "o_statistiques": {
        "diagram": "/static/illustrations/diagram_statistics.jpg",
        "author_name": "Divers",
        "author_years": "1900-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "Fisher, R.A. (1925). Statistical Methods for Research Workers.",
        "simulation_template": "statistics",
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "Les statistiques inférentielles ont été développées au début du 20e siècle par Fisher, Pearson, Neyman et d'autres pour analyser les données expérimentales.",
        "how_to_use": "1. Définir l'hypothèse nulle (H0) et alternative (H1).\n2. Choisir le test approprié selon le type de données et le design.\n3. Calculer la statistique de test et la p-value.\n4. Interpréter selon le seuil alpha (généralement 0.05).",
        "advantages": ["Rigueur scientifique", "Objectivité", "Reproductibilité", "Standards établis"],
        "limitations": ["Dépend des hypothèses", "p-value mal interprétée", "Taille d'effet souvent ignorée", "Biais de publication"],
        "real_world": [
            {"domain": "Recherche", "desc": "Validation d'hypothèses dans toutes les disciplines scientifiques."},
            {"domain": "Médecine", "desc": "Essais cliniques, études épidémiologiques."},
            {"domain": "Psychologie", "desc": "Analyse des données expérimentales et observationnelles."}
        ],
        "key_results": {"figure_desc": "Distribution normale avec zones de rejet (α=0.05)", "stats": "Seuil standard : α=0.05. Puissance recommandée : 0.80. Taille d'effet : Cohen's d, η², r."}
    },
    "o_jasp": {
        "diagram": None,
        "author_name": "JASP Team",
        "author_years": "2014-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "JASP Team (2024). JASP (Version 0.18.3) [Computer software].",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_statistiques"],
        "history": "JASP (Jeffreys's Amazing Statistics Program) est un logiciel gratuit développé pour faciliter l'analyse statistique bayésienne et fréquentiste.",
        "how_to_use": "1. Importer les données (CSV, SPSS, Excel).\n2. Choisir l'analyse (T-tests, ANOVA, régression, etc.).\n3. Configurer les variables et options.\n4. Interpréter les résultats avec tableaux et graphiques automatiques.",
        "advantages": ["Gratuit et open-source", "Interface intuitive", "Statistiques bayésiennes intégrées", "Graphiques automatiques", "Compatible avec R"],
        "limitations": ["Moins flexible que R pour analyses complexes", "Communauté plus petite que SPSS/R"],
        "real_world": [
            {"domain": "Recherche", "desc": "Alternative gratuite à SPSS avec statistiques bayésiennes."},
            {"domain": "Enseignement", "desc": "Outil pédagogique pour apprendre les statistiques."},
            {"domain": "Psychologie", "desc": "Très populaire dans la communauté psychologique."}
        ],
        "key_results": {"figure_desc": "Interface JASP avec tableau de résultats et graphiques", "stats": "Tests disponibles : T-tests, ANOVA, régression, corrélations, tests non-paramétriques, Bayes."}
    },
    "o_r": {
        "diagram": None,
        "author_name": "R Core Team",
        "author_years": "1993-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "R Core Team (2024). R: A language and environment for statistical computing.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_statistiques"],
        "history": "R est un langage de programmation et environnement statistique créé par Ross Ihaka et Robert Gentleman en 1993.",
        "how_to_use": "1. Installer R et RStudio.\n2. Charger les packages nécessaires (tidyverse, lme4, etc.).\n3. Écrire le script d'analyse.\n4. Exécuter et interpréter les résultats.",
        "advantages": ["Gratuit et open-source", "Extrêmement flexible", "18 000+ packages", "Communauté énorme", "Reproductibilité"],
        "limitations": ["Courbe d'apprentissage raide", "Programmation requise", "Gestion mémoire pour gros datasets"],
        "real_world": [
            {"domain": "Recherche", "desc": "Standard de facto dans de nombreuses disciplines scientifiques."},
            {"domain": "Data Science", "desc": "Analyse de données, visualisation, machine learning."},
            {"domain": "Bioinformatique", "desc": "Bioconductor pour l'analyse génomique."}
        ],
        "key_results": {"figure_desc": "Console R avec code et graphiques ggplot2", "stats": "Packages populaires : tidyverse, ggplot2, lme4, brms, lavaan."}
    },
    "o_python_stats": {
        "diagram": None,
        "author_name": "Python Community",
        "author_years": "1991-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "Van Rossum, G. (1991). Python Programming Language.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_statistiques"],
        "history": "Python est devenu un langage majeur pour l'analyse scientifique grâce à des bibliothèques comme NumPy, SciPy, pandas et statsmodels.",
        "how_to_use": "1. Installer Python avec Anaconda ou pip.\n2. Importer les bibliothèques (pandas, scipy.stats, statsmodels).\n3. Charger et nettoyer les données.\n4. Effectuer les analyses statistiques.",
        "advantages": ["Langage généraliste", "Écosystème riche", "Intégration ML/DL", "Visualisation (matplotlib, seaborn)"],
        "limitations": ["Moins spécialisé que R pour statistiques", "Syntaxe plus verbeuse pour certaines analyses"],
        "real_world": [
            {"domain": "Data Science", "desc": "Pipeline complet : données → analyse → ML → déploiement."},
            {"domain": "Recherche", "desc": "Alternative à R, surtout en neurosciences computationnelles."},
            {"domain": "Industrie", "desc": "Analyse de données produit, A/B testing."}
        ],
        "key_results": {"figure_desc": "Jupyter notebook avec code Python et visualisations", "stats": "Bibliothèques : scipy.stats, statsmodels, pingouin, scikit-learn."}
    },
    "o_csv_processing": {
        "diagram": None,
        "author_name": "Divers",
        "author_years": "1970-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "Shafer, J. (1972). The CSV format specification.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": [],
        "history": "Le format CSV (Comma-Separated Values) est un format de fichier texte simple pour stocker des données tabulaires.",
        "how_to_use": "1. Exporter les données en CSV depuis l'expérience.\n2. Nettoyer les données (valeurs manquantes, outliers).\n3. Importer dans le logiciel d'analyse (R, Python, JASP).\n4. Effectuer les analyses statistiques.",
        "advantages": ["Format universel", "Lisible par humain", "Compatible avec tous les logiciels", "Léger"],
        "limitations": ["Pas de métadonnées", "Problèmes d'encodage", "Pas de types de données"],
        "real_world": [
            {"domain": "Recherche", "desc": "Format standard pour échanger des données entre chercheurs."},
            {"domain": "Industrie", "desc": "Export de données depuis applications web et bases de données."},
            {"domain": "Open Data", "desc": "Publication de données gouvernementales et scientifiques."}
        ],
        "key_results": {"figure_desc": "Fichier CSV ouvert dans tableur", "stats": "Bonnes pratiques : UTF-8, séparateur virgule, guillemets pour texte, pas de cellules fusionnées."}
    },
    "o_eeg_processing": {
        "diagram": "/static/illustrations/diagram_eeg.jpg",
        "author_name": "Divers",
        "author_years": "1924-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "Berger, H. (1929). Über das Elektrenkephalogramm des Menschen.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_eeg"],
        "history": "Le traitement des signaux EEG a évolué depuis l'invention de l'EEG par Hans Berger en 1924.",
        "how_to_use": "1. Prétraitement : filtrage (0.1-30 Hz), rejection d'artefacts.\n2. Segmentation en epochs autour des stimuli.\n3. Moyennage pour obtenir les ERP.\n4. Analyse statistique des amplitudes et latences.",
        "advantages": ["Résolution temporelle excellente", "Non-invasif", "Portable", "Coût modéré"],
        "limitations": ["Résolution spatiale faible", "Artefacts nombreux", "Traitement complexe"],
        "real_world": [
            {"domain": "Recherche cognitive", "desc": "Étude des processus cognitifs avec résolution temporelle milliseconde."},
            {"domain": "Clinique", "desc": "Diagnostic d'épilepsie, troubles du sommeil."},
            {"domain": "BCI", "desc": "Interfaces cerveau-machine pour contrôle de prothèses."}
        ],
        "key_results": {"figure_desc": "Signal EEG brut et ERP moyenné", "stats": "Logiciels : EEGLAB (MATLAB), MNE-Python, FieldTrip. Fréquence d'échantillonnage : 256-1024 Hz."}
    },
    "o_ia_statistiques": {
        "diagram": None,
        "author_name": "Divers",
        "author_years": "2020-présent",
        "author_image": None,
        "doi": None,
        "seminal_paper": "OpenAI (2023). GPT-4 Technical Report.",
        "simulation_template": None,
        "lab_tools": [],
        "related_concepts_ids": ["o_statistiques"],
        "history": "Les IA génératives comme GPT-4 et Claude peuvent aider à l'analyse statistique en générant du code, en interprétant des résultats et en suggérant des analyses.",
        "how_to_use": "1. Décrire les données et la question de recherche à l'IA.\n2. Demander le code R/Python approprié.\n3. Vérifier et adapter le code généré.\n4. Interpréter les résultats avec l'aide de l'IA.",
        "advantages": ["Aide à la rédaction de code", "Suggestions d'analyses", "Interprétation des résultats", "Documentation automatique"],
        "limitations": ["Peut générer du code incorrect", "Nécessite vérification humaine", "Pas de compréhension réelle des données"],
        "real_world": [
            {"domain": "Recherche", "desc": "Assistant pour chercheurs débutants en statistiques."},
            {"domain": "Enseignement", "desc": "Outil pédagogique pour apprendre les statistiques."},
            {"domain": "Industrie", "desc": "Automatisation de rapports statistiques."}
        ],
        "key_results": {"figure_desc": "Conversation avec IA pour analyse statistique", "stats": "IA populaires : GPT-4, Claude, Gemini. Précision : 70-90% pour code statistique standard."}
    }
}

def get_data_processing_tool(tool_id):
    return DATA_PROCESSING_TOOLS.get(tool_id)

def get_all_data_processing_tools():
    return DATA_PROCESSING_TOOLS
